Hotfix/4.4.2
WildGums/Orc.Skia pull request #490
Opened 2022-11-01 23:43 UTC by Averus-a

### Description of Change ###

Add Lottie animations support to Orc.Skia
- [x] Canvas control playing animations
- [x] Support setting source with pack Uri and stream
- [x] Control repeat behavior
- [x] Get animation info with bindings
- [ ] Mouse over behavior?
- [ ] Explicit pause/ play control?

### Issues Resolved ### 

- fixes #

### API Changes ###

 
None

### Platforms Affected ### 

- All
- WPF
- UWP
- iOS
- Android

### Behavioral Changes ###

None

### Testing Procedure ###

### PR Checklist ###

- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

2022-11-02 08:48 UTC, GeertvanHorrik requested changes

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia.Example.NET/ViewModels/LottieAnimationsTestViewModel.cs
> +    using Catel.MVVM;
remove unused usings

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia.Example.NET/Views/LottieAnimationsTestView.xaml
> +                                     Filter="Файлы Lottie (*.json)|*.json"/>
Filter seems incorrect

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia.Example.NET/Views/LottieAnimationsTestView.xaml
> +                <Grid>
stackgrid?

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +        private const float FramePerSeconds = 60;
do we want to be able to customize this (per control) or is this fixed because of Lottie animations?

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +            IsPlaying = false;
SetCurrentValue?

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +            Argument.IsNotNull(() => animation);
ArgumentNullException.ThrowIfNull()

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +            Argument.IsNotNull(() => animation);
ArgumentNullException.ThrowIfNull

2022-11-02 08:48 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +            Log.Debug($"Frame render time: {renderTime} ms");
wrap with #if DEBUG, we don't need this in production apps

2022-11-05 00:28 UTC, Averus-a commented on src/Orc.Skia/LottieCanvas.cs
> +        private const float FramePerSeconds = 60;
I think technically animation file could be designed for any cound for frames per second, but techically 99,9% animations made with BodyMovin extensions for AE and exported for multiplatform would be 60 fps, because otherwise some devices (e.g. Iphone) will not render them correctly in apps.

2022-11-05 00:42 UTC, Averus-a commented on src/Orc.Skia/LottieCanvas.cs
> +        public bool Repeat
Done

2022-11-05 00:47 UTC, Averus-a commented on src/Orc.Skia/LottieCanvas.cs
> +            set => SetValue(IsPlayingProperty, value);
Throwing exception now, same as modyfing Animation directly

2022-11-05 01:48 UTC, Averus-a commented
Last commit introduced changeable behavior on mouse hover.
I've named enum as `AnimationMouseOverBehavior` but it's not coherent with `RepeatBehavior`
I am thinking should we keep it as-is or add `Orc.Skia.Animation` namespace and omit animation word from enum name.

2022-11-05 12:35 UTC, GeertvanHorrik requested changes

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia.Example.NET/ViewModels/LottieAnimationsTestViewModel.cs
> +
remove empty line

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia.Example.NET/ViewModels/LottieAnimationsTestViewModel.cs
> +            MouseOverBehavior = (AnimationMouseOverBehavior)int.Parse(arg);
I think we can use Enum<AnimationMouseOverBehavior>.Parse instead?

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia.Example.NET/Views/LottieAnimationsTestView.xaml
> +                                 Command="{Binding SetMouseOverBehaviorCommand}" CommandParameter="0"/>
I think you can even work with actual names here (see vm comment about enum.parse)

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia/AnimationMouseOverBehavior.cs
> +        None,
Always explicitly add numbers to the enum values. If there is a tool (e.g. R#) or human that will change this based on alphabetically order, it gets messed up.

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia/Converters/BooleanToRepeatBehaviorConverter.cs
> +            return value ? RepeatBehavior.Forever : new RepeatBehavior(1);
Cache RepeatBeahvior in ctor, we don't need to create a new instance all the time.

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +        public static readonly DependencyProperty IsPlayingProperty =
Since this one will write back, can we use FrameworkMetadata.OneWayToSource or TwoWay by default?

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +        private const float FramePerSeconds = 60;
FramesPerSecond (plural)

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +
remove empty line

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +            else
I think the else can be removed for code readability since we already return when repeat is forever

2022-11-05 12:35 UTC, GeertvanHorrik commented on src/Orc.Skia/LottieCanvas.cs
> +            animation.Render(canvas, new SKRect(0, 0, (float)ActualWidth, (float)ActualHeight));
Question to think about: would it make sense to cache ActualWidth / ActualHeight in a field and update during resize? Not sure if it's worth the optimization though

2022-11-05 17:44 UTC, Averus-a commented on src/Orc.Skia.Example.NET/ViewModels/LottieAnimationsTestViewModel.cs
> +            MouseOverBehavior = (AnimationMouseOverBehavior)int.Parse(arg);
I am not sure what do you mean. Arg is string number, not an enum value

2022-11-05 17:44 UTC, Averus-a commented on src/Orc.Skia.Example.NET/ViewModels/LottieAnimationsTestViewModel.cs
> +            MouseOverBehavior = (AnimationMouseOverBehavior)int.Parse(arg);
got it, sorry

2022-11-05 18:18 UTC, Averus-a commented on src/Orc.Skia/LottieCanvas.cs
> +            animation.Render(canvas, new SKRect(0, 0, (float)ActualWidth, (float)ActualHeight));
I don't have it will be any difference

2022-11-05 18:18 UTC, Averus-a commented on src/Orc.Skia/LottieCanvas.cs
> +        public static readonly DependencyProperty IsPlayingProperty =
Very good idea

2022-11-05 18:24 UTC, Averus-a commented on src/Orc.Skia/LottieCanvas.cs
> +        public static readonly DependencyProperty IsPlayingProperty =
It appears you can only choose TwoWay by default or not (without specifying type) and change UpdateSourceTrigger.

2022-11-11 10:57 UTC, merged